/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GalleryImage = IDL.Record({
  'title' : IDL.Text,
  'caption' : IDL.Text,
});
export const MenuCategory = IDL.Variant({
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'specials' : IDL.Null,
  'dinner' : IDL.Null,
  'beverages' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : MenuCategory,
  'price' : IDL.Nat,
  'vegetarian' : IDL.Bool,
});
export const RestaurantInfo = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [MenuCategory],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  'getSortedMenuByCategory' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getVegMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GalleryImage = IDL.Record({ 'title' : IDL.Text, 'caption' : IDL.Text });
  const MenuCategory = IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'specials' : IDL.Null,
    'dinner' : IDL.Null,
    'beverages' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : MenuCategory,
    'price' : IDL.Nat,
    'vegetarian' : IDL.Bool,
  });
  const RestaurantInfo = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [MenuCategory],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
    'getSortedMenuByCategory' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getVegMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };