/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'itemName' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceEach' : IDL.Nat,
});
export const CustomerOrder = IDL.Record({
  'orderId' : IDL.Nat,
  'totalAmount' : IDL.Nat,
  'timestamp' : Time,
  'items' : IDL.Vec(OrderItem),
});
export const GalleryImage = IDL.Record({
  'title' : IDL.Text,
  'caption' : IDL.Text,
});
export const MenuCategory = IDL.Variant({
  'breakfast' : IDL.Null,
  'lunch' : IDL.Null,
  'specials' : IDL.Null,
  'dinner' : IDL.Null,
  'beverages' : IDL.Null,
});
export const MenuItem = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : MenuCategory,
  'price' : IDL.Nat,
  'vegetarian' : IDL.Bool,
});
export const RestaurantInfo = IDL.Record({
  'name' : IDL.Text,
  'whatsapp' : IDL.Text,
  'address' : IDL.Text,
  'openingHours' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAdminOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getAdminOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getMenuItemsByCategory' : IDL.Func(
      [MenuCategory],
      [IDL.Vec(MenuItem)],
      ['query'],
    ),
  'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
  'getSortedMenuByCategory' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getVegMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Nat], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'itemName' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceEach' : IDL.Nat,
  });
  const CustomerOrder = IDL.Record({
    'orderId' : IDL.Nat,
    'totalAmount' : IDL.Nat,
    'timestamp' : Time,
    'items' : IDL.Vec(OrderItem),
  });
  const GalleryImage = IDL.Record({ 'title' : IDL.Text, 'caption' : IDL.Text });
  const MenuCategory = IDL.Variant({
    'breakfast' : IDL.Null,
    'lunch' : IDL.Null,
    'specials' : IDL.Null,
    'dinner' : IDL.Null,
    'beverages' : IDL.Null,
  });
  const MenuItem = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : MenuCategory,
    'price' : IDL.Nat,
    'vegetarian' : IDL.Bool,
  });
  const RestaurantInfo = IDL.Record({
    'name' : IDL.Text,
    'whatsapp' : IDL.Text,
    'address' : IDL.Text,
    'openingHours' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAdminOrderCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getAdminOrders' : IDL.Func([], [IDL.Vec(CustomerOrder)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getMenuItemsByCategory' : IDL.Func(
        [MenuCategory],
        [IDL.Vec(MenuItem)],
        ['query'],
      ),
    'getRestaurantInfo' : IDL.Func([], [RestaurantInfo], ['query']),
    'getSortedMenuByCategory' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getVegMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Nat], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };