/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CustomerOrder {
  'orderId' : bigint,
  'totalAmount' : bigint,
  'timestamp' : Time,
  'items' : Array<OrderItem>,
}
export interface GalleryImage { 'title' : string, 'caption' : string }
export type MenuCategory = { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'specials' : null } |
  { 'dinner' : null } |
  { 'beverages' : null };
export interface MenuItem {
  'name' : string,
  'description' : string,
  'category' : MenuCategory,
  'price' : bigint,
  'vegetarian' : boolean,
}
export interface OrderItem {
  'itemName' : string,
  'quantity' : bigint,
  'priceEach' : bigint,
}
export interface RestaurantInfo {
  'name' : string,
  'whatsapp' : string,
  'address' : string,
  'openingHours' : string,
  'phone' : string,
}
export type Time = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAdminOrderCount' : ActorMethod<[], bigint>,
  'getAdminOrders' : ActorMethod<[], Array<CustomerOrder>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[MenuCategory], Array<MenuItem>>,
  'getRestaurantInfo' : ActorMethod<[], RestaurantInfo>,
  'getSortedMenuByCategory' : ActorMethod<[], Array<MenuItem>>,
  'getVegMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[Array<OrderItem>, bigint], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];