/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface GalleryImage { 'title' : string, 'caption' : string }
export type MenuCategory = { 'breakfast' : null } |
  { 'lunch' : null } |
  { 'specials' : null } |
  { 'dinner' : null } |
  { 'beverages' : null };
export interface MenuItem {
  'name' : string,
  'description' : string,
  'category' : MenuCategory,
  'price' : bigint,
  'vegetarian' : boolean,
}
export interface RestaurantInfo {
  'name' : string,
  'whatsapp' : string,
  'address' : string,
  'openingHours' : string,
  'phone' : string,
}
export interface _SERVICE {
  'getGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getMenuItemsByCategory' : ActorMethod<[MenuCategory], Array<MenuItem>>,
  'getRestaurantInfo' : ActorMethod<[], RestaurantInfo>,
  'getSortedMenuByCategory' : ActorMethod<[], Array<MenuItem>>,
  'getVegMenuItems' : ActorMethod<[], Array<MenuItem>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];